//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoiceGenerator
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InvoiceEntities : DbContext
    {
        public InvoiceEntities()
            : base("name=InvoiceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblCustomer> tblCustomer { get; set; }
        public virtual DbSet<tblDescription> tblDescription { get; set; }
        public virtual DbSet<tblInvoice> tblInvoice { get; set; }
        public virtual DbSet<tblInvoiceDetail> tblInvoiceDetail { get; set; }
        public virtual DbSet<tblUser> tblUser { get; set; }
        public virtual DbSet<VwDescription> VwDescription { get; set; }
        public virtual DbSet<VwInvoice> VwInvoice { get; set; }
        public virtual DbSet<VwInvoiceList> VwInvoiceList { get; set; }
        public virtual DbSet<VwInvoiceReport> VwInvoiceReport { get; set; }
    }
}
