//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoiceGenerator
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwInvoice
    {
        public string CustomerName { get; set; }
        public string Email { get; set; }
        public int InvoiceID { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public string ContactNo { get; set; }
        public string Address { get; set; }
        public string BusinessName { get; set; }
        public string BusinessAddress { get; set; }
        public string BusinessWebsite { get; set; }
        public Nullable<decimal> GST { get; set; }
        public string Terms { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Duration { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public int InvoiceDetailID { get; set; }
    }
}
